CREATE TABLE chainsysregister(Id NUMBER(15) PRIMARY KEY ,name VARCHAR(15),password VARCHAR(15),email VARCHAR(15) NOT NULL,sex VARCHAR(10),department VARCHAR(25));
SELECT * FROM  CHAINSYSREGISTER;

CREATE TABLE SIGNUP(USERNAME VARCHAR(15),EMAIL VARCHAR(15),PASSWORD VARCHAR(15),CONFIRM_PASSWORD varchar(15));
SELECT * FROM  SIGNUP;

CREATE TABLE CODE(ADMINID INT NOT NULL UNIQUE,CODE NUMBER(4) NOT NULL);
SELECT * FROM CODE;
commit;
INSERT INTO CODE VALUES(2109,1998);
INSERT INTO CODE VALUES(2209,1999);
INSERT INTO CODE VALUES(2309,2000);
INSERT INTO CODE VALUES(2409,2001);
INSERT INTO CODE VALUES(2509,2002);
commit;

